Revert "window: make content_header_bar a GtkGrid"
This reverts commit 779912c2912e63ebf6c50e0722798f9ecfedc617.

The commit breaks the build in Continuous (and locally), because of a
reference to `content_header_bar` being a Gtk.Box:

contacts-window.vala:54.3-54.32: error: cannot convert from Gtk child
type `Gtk.Grid' to `Gtk.Box'
  private Box content_header_bar;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Compilation failed: 1 error(s), 140 warning(s)

I'm reverting the commit as per:

  https://mail.gnome.org/archives/desktop-devel-list/2016-January/msg00015.html

because the Continuous break has been failing for more than 4 hours.

https://bugzilla.gnome.org/show_bug.cgi?id=761759